export const UPDATE_INPUT_URL_VALUE = 'UPDATE_INPUT_URL_VALUE';
export const UPDATE_JAE_URL = 'UPDATE_JAE_URL';
export const UPDATE_URL_VALIDITY = 'UPDATE_URL_VALIDITY';
export const FETCH_JAE_URL = 'FETCH_JAE_URL';
export const FETCH_JAE_URL_SUCCESS = 'FETCH_JAE_URL_SUCCESS';
export const FETCH_JAE_URL_FAILURE = 'FETCH_JAE_URL_FAILURE';
export const STARTED_FETCHING_JAE_URL = 'STARTED_FETCHING_JAE_URL';
export const FINISHED_FETCHING_JAE_URL = 'FINISHED_FETCHING_JAE_URL';
