export const UPDATE_INPUT_URL_VALUE = 'UPDATE_INPUT_URL_VALUE';
export const UPDATE_JAE_URL = 'UPDATE_JAE_URL';
export const UPDATE_URI_VALIDITY = 'UPDATE_URI_VALIDITY';
export const FETCH_JAE_URL = 'FETCH_JAE_URL';
export const FETCH_JAE_URL_SUCCESS = 'FETCH_JAE_URL_SUCCESS';
export const FETCH_JAE_URL_FAILURE = 'FETCH_JAE_URL_FAILURE';
